# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mani Monajjemi
tagline:          "Personal Website"
description:      ''
url:              https://mani.im
enforce_ssl:      mani.im
baseurl:          /

author:
  name:           'Mani Monajjemi'
  url:            https://twitter.com/mani_monaj

paginate:         5

# Custom vars
version:          0.1-dev

github:
  repo:           https://github.com/mani-monaj/mani-monaj.github.io

gems:
  - jekyll-sitemap
